# Generated by Django 4.1.2 on 2022-12-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seller", "0003_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product", name="discount", field=models.FloatField(default=0.0),
        ),
    ]
