# Generated by Django 4.1.2 on 2022-12-17 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("seller", "0004_product_discount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product", old_name="discount", new_name="dis_price",
        ),
    ]
