# Generated by Django 4.1.3 on 2022-11-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buyer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyer",
            name="pic",
            field=models.FileField(default="avtar.webp", upload_to="profile/"),
        ),
    ]
