# Generated by Django 4.1.2 on 2022-12-26 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("buyer", "0007_cart"),
    ]

    operations = [
        migrations.RemoveField(model_name="cart", name="quantity",),
    ]
